// report/renderHtml.js  (FULL FILE)

function esc(s) {
  return String(s || "")
    .replace(/&/g, "&amp;")
    .replace(/</g, "&lt;")
    .replace(/>/g, "&gt;")
    .replace(/"/g, "&quot;");
}

function prettyIso(iso) {
  try {
    const d = new Date(iso);
    if (!Number.isFinite(d.getTime())) return iso;
    return d.toLocaleString(undefined, {
      year: "numeric",
      month: "short",
      day: "numeric",
      hour: "numeric",
      minute: "2-digit"
    });
  } catch {
    return iso;
  }
}

export function renderReportHtml({ title, question, answerText, snapshotId, generatedAtIso, meta }) {
  const safeTitle = esc(title || "FarmVista Report");
  const safeQuestion = esc(question || "");
  const safeAnswer = esc(answerText || "");

  const generated = prettyIso(generatedAtIso || new Date().toISOString());
  const safeSnap = esc(snapshotId || "unknown");

  // Small, consistent report theme. No external assets.
  // (You can later swap in TT Moons + FarmVista tokens if you want.)
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8" />
  <title>${safeTitle}</title>
  <meta name="viewport" content="width=device-width, initial-scale=1" />
  <style>
    :root{
      --fv-green:#3B7E46;
      --ink:#111827;
      --muted:#6B7280;
      --border:#E5E7EB;
      --bg:#FFFFFF;
      --chip:#F3F4F6;
    }
    *{ box-sizing:border-box; }
    body{
      margin:0;
      font-family: ui-sans-serif, system-ui, -apple-system, Segoe UI, Roboto, Helvetica, Arial;
      color:var(--ink);
      background:var(--bg);
    }
    .page{
      padding:28px 32px 34px;
    }
    .hdr{
      display:flex;
      justify-content:space-between;
      gap:16px;
      align-items:flex-start;
      border-bottom:2px solid var(--border);
      padding-bottom:14px;
      margin-bottom:18px;
    }
    .brand{
      display:flex;
      flex-direction:column;
      gap:6px;
    }
    .brand .logo{
      font-weight:900;
      letter-spacing:.02em;
      font-size:18px;
      color:var(--fv-green);
    }
    .brand .sub{
      font-size:12px;
      color:var(--muted);
      line-height:1.2;
    }
    .title{
      margin:0;
      font-size:22px;
      line-height:1.15;
      font-weight:900;
      letter-spacing:.01em;
    }
    .meta{
      text-align:right;
      font-size:12px;
      color:var(--muted);
      line-height:1.35;
      min-width:240px;
    }
    .chiprow{
      margin-top:10px;
      display:flex;
      flex-wrap:wrap;
      gap:8px;
    }
    .chip{
      font-size:11px;
      padding:6px 10px;
      border-radius:999px;
      background:var(--chip);
      border:1px solid var(--border);
      color:#374151;
      white-space:nowrap;
    }
    .section{
      margin:18px 0 0;
    }
    .section h2{
      margin:0 0 8px;
      font-size:14px;
      letter-spacing:.06em;
      text-transform:uppercase;
      color:#111827;
    }
    .box{
      border:1px solid var(--border);
      border-radius:12px;
      padding:12px 14px;
      background:#fff;
    }
    pre{
      margin:0;
      white-space:pre-wrap;
      word-break:break-word;
      font-family: ui-monospace, SFMono-Regular, Menlo, Monaco, Consolas, "Liberation Mono", "Courier New", monospace;
      font-size:12px;
      line-height:1.35;
      color:#111827;
    }
    .footer{
      margin-top:18px;
      font-size:11px;
      color:var(--muted);
      border-top:1px solid var(--border);
      padding-top:10px;
      display:flex;
      justify-content:space-between;
      gap:12px;
    }
  </style>
</head>
<body>
  <div class="page">
    <div class="hdr">
      <div class="brand">
        <div class="logo">FarmVista</div>
        <div class="sub">Copilot Report</div>
        <div class="chiprow">
          <span class="chip">Snapshot: ${safeSnap}</span>
          <span class="chip">Generated: ${esc(generated)}</span>
        </div>
      </div>

      <div class="meta">
        <h1 class="title">${safeTitle}</h1>
      </div>
    </div>

    <div class="section">
      <h2>Prompt</h2>
      <div class="box">
        <pre>${safeQuestion}</pre>
      </div>
    </div>

    <div class="section">
      <h2>Result</h2>
      <div class="box">
        <pre>${safeAnswer}</pre>
      </div>
    </div>

    <div class="footer">
      <div>Generated by FarmVista Copilot</div>
      <div>${meta && meta.threadId ? `Thread: ${esc(meta.threadId)}` : ""}</div>
    </div>
  </div>
</body>
</html>`;
}
